certificate:
  enabled: true
  issuerName: http-issuer
  issuerKind: ClusterIssuer

docs: true

ingress:
  enabled: true
  annotations: {}

resources:
  requests:
    memory: '512Mi'
    cpu: '50m'
  limits:
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

envFrom:
  - secretRef:
      name: bahn-expert-config
